# Generated by Django 5.2.2 on 2025-06-17 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_topic_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(blank=True, to='myapp.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
