# Generated by Django 5.2.2 on 2025-06-17 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_topics_topic_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='subscribed_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
